<?php

namespace Amplify\System\Sayt\Widgets;

use Amplify\Frontend\Abstracts\BaseComponent;
use Closure;
use Illuminate\Contracts\View\View;

/**
 * @class ShopSearchInResult
 */
class ShopSearchInResult extends BaseComponent
{
    public string $uuid;

    /**
     * Create a new component instance.
     */
    public function __construct(public string $title = 'SEARCH WITHIN RESULTS', public string $btnLabel = 'Go', public int $minLength = 3)
    {
        parent::__construct();

        $this->uuid = 'search-results-'.mt_rand(1000, 9999);

    }

    /**
     * Whether the component should be rendered
     */
    public function shouldRender(): bool
    {
        return config('amplify.sayt.enabled', true);
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('sayt::shop-search-in-result');
    }

    public function htmlAttributes(): string
    {
        $this->attributes = $this->attributes->class(['mb-1 widget']);

        return parent::htmlAttributes(); // TODO: Change the autogenerated stub
    }

    public function searchBoxPlaceholder()
    {
        return config('amplify.sayt.search_box_placeholder');
    }

    public function currentUrl()
    {
        $extraQuery = [
            'view' => active_shop_view(),
            'per_page' => request('per_page', getPaginationLengths()[0]),
            'sort_by' => request('sort_by'),
        ];

        $seoPath = rtrim(store()->eaProductsData->getCurrentSeoPath());

        return frontendShopURL([$seoPath, ...$extraQuery]);
    }

    public function showKeyword()
    {
        $route = request()->route();

        if ($route->getName() != 'frontend.shop.index') {
            return '';
        }

        $params = $route->parameter('query');

        if (!empty($params) && $params != 'search' & request()->filled('q')) {
            return store()->eaProductsData->getOriginalQuestion();
        }

        return '';
    }
}
