name: Compile Develop Mix Assets

on:
  push:

permissions:
  contents: write

jobs:
  laravel-mix-asset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Compile Develop Assets
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: npm install --force
      - run: npm run prod

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "compile laravel mix assets"
